class_name BulletPatternData
extends Resource

enum {
	SOUL_MODE_NORMAL,
	SOUL_MODE_BULLETS_SOUTH,
	SOUL_MODE_BULLETS_NORTH,
	SOUL_MODE_BULLETS_EAST,
	SOUL_MODE_BULLETS_WEST,
	SOUL_MODE_GRAVITY_SOUTH,
	SOUL_MODE_GRAVITY_NORTH,
	SOUL_MODE_GRAVITY_EAST,
	SOUL_MODE_GRAVITY_WEST,
	SOUL_MODE_SHIELDED,
	SOUL_MODE_LANES_VERTICAL,
	SOUL_MODE_LANES_HORIZONTAL,
	SOUL_MODE_POINTS,
	SOUL_MODE_TORCH,
	SOUL_MODE_DASH_SOUTH,
	SOUL_MODE_DASH_NORTH,
	SOUL_MODE_DASH_EAST,
	SOUL_MODE_DASH_WEST,
}

@export var name: String
@export var bullets: Array[BulletData]
# -1 means wait until the animation is finished
@export var end_time: float = -1
